import { test, expect, type Page } from "@playwright/test";
import { createHash } from "node:crypto";

/**
 * LAUNCH #20 — the public-ready DeCA happy path, end to end, from a clean
 * session. Automates the steps that CAN be automated; the QR scan from a
 * second physical device is in `docs/production-smoke-checklist.md`.
 *
 * PRIORITY 1 (product hardening directive) superseded the old "no signup
 * wall" design: a DeCA can now only be FINALLY generated by a registered,
 * authenticated user. A visitor may still fill every step anonymously — the
 * draft is preserved (sessionStorage) and restored with no retyping once they
 * register or log in.
 *
 * Launch blockers this spec fails on: an anonymous caller ever getting a real
 * document, mock/fake document, QR pointing at the wrong host, `/d/[token]`
 * returning HTML, missing legal fields, PDF changing between fetches, the
 * draft being lost across the registration redirect.
 */

const DECA = {
  shipperName: "Cargas del Turia SL",
  shipperNif: "B96789011",
  shipperAddress: "Av. del Puerto 120, Valencia",
  carrierName: "Transportes Pérez SL",
  carrierNif: "B12345674",
  carrierAddress: "Pol. Ind. Fuente del Jarro, calle 5, Paterna",
  loadLocationName: "Almacén Turia",
  loadLocationAddress: "Av. del Puerto 120",
  loadLocationPostalCode: "46023",
  loadLocationCity: "Valencia",
  loadLocationProvince: "Valencia",
  loadLocationCountry: "España",
  loadDate: "2026-10-06",
  unloadLocationName: "Plataforma Norte",
  unloadLocationAddress: "Calle Alcalá 200",
  unloadLocationPostalCode: "28028",
  unloadLocationCity: "Madrid",
  unloadLocationProvince: "Madrid",
  unloadLocationCountry: "España",
  unloadDate: "2026-10-06",
  goods: "Palés de cerámica",
  weight: "12.500 kg",
  tractorPlate: "1234 BCD",
};

function email() {
  return `lhp${Date.now()}${Math.floor(Math.random() * 1e5)}@example.com`;
}

async function fillWizardAnon(page: Page) {
  await page.fill("#shipperName", DECA.shipperName);
  await page.fill("#shipperNif", DECA.shipperNif);
  await page.fill("#shipperAddress", DECA.shipperAddress);
  await page.fill("#carrierName", DECA.carrierName);
  await page.fill("#carrierNif", DECA.carrierNif);
  await page.fill("#carrierAddress", DECA.carrierAddress);
  await page.getByTestId("wizard-next").click();
  await page.fill("#loadLocationName", DECA.loadLocationName);
  await page.fill("#loadLocationAddress", DECA.loadLocationAddress);
  await page.fill("#loadLocationPostalCode", DECA.loadLocationPostalCode);
  await page.fill("#loadLocationCity", DECA.loadLocationCity);
  await page.fill("#loadLocationProvince", DECA.loadLocationProvince);
  await page.fill("#loadLocationCountry", DECA.loadLocationCountry);
  await page.fill("#loadDate", DECA.loadDate);
  await page.fill("#unloadLocationName", DECA.unloadLocationName);
  await page.fill("#unloadLocationAddress", DECA.unloadLocationAddress);
  await page.fill("#unloadLocationPostalCode", DECA.unloadLocationPostalCode);
  await page.fill("#unloadLocationCity", DECA.unloadLocationCity);
  await page.fill("#unloadLocationProvince", DECA.unloadLocationProvince);
  await page.fill("#unloadLocationCountry", DECA.unloadLocationCountry);
  await page.fill("#unloadDate", DECA.unloadDate);
  await page.getByTestId("wizard-next").click();
  await page.fill("#goods", DECA.goods);
  await page.fill("#weight", DECA.weight);
  await page.fill("#tractorPlate", DECA.tractorPlate);
}

test.describe("LAUNCH #20 — production happy path", () => {
  test("anonymous draft → registration gate → draft restored, no retyping → PDF → QR-equivalent → duplicate", async ({
    page,
    request,
    baseURL,
  }) => {
    // 1-2. Landing → CREAR DECA GRATIS (mobile viewport)
    await page.setViewportSize({ width: 360, height: 740 });
    await page.goto("/");
    await expect(page.locator("h1")).toHaveText(
      "DeCA profesional, sencillo y listo para trabajar.",
    );
    await page.getByTestId("cta-crear").first().click();
    await expect(page).toHaveURL(/\/crear$/);
    // no signup wall to START filling data — only to finally generate
    await expect(page.getByText("Completa los datos sin compromiso")).toBeVisible();

    // 3-4. Complete a legally valid DeCA + review the exact final data
    await fillWizardAnon(page);
    const review = page.getByTestId("review-summary");
    await expect(review).toBeVisible();
    for (const v of [
      DECA.shipperAddress,
      DECA.carrierAddress,
      DECA.unloadLocationCity,
      DECA.weight,
      DECA.tractorPlate,
    ]) {
      await expect(review).toContainText(v);
    }

    // 5. PRIORITY 1: the generate button is replaced by the registration gate —
    // an anonymous visitor cannot finally generate the document.
    await expect(page.getByTestId("wizard-generate")).toHaveCount(0);
    await expect(page.getByTestId("auth-gate")).toBeVisible();

    // 6. Register in the SAME tab — the draft (sessionStorage) must survive.
    await page.getByTestId("auth-gate-register").click();
    await expect(page).toHaveURL(/\/registro\?next=%2Fcrear/);
    await page.fill("#email", email());
    await page.fill("#password", "supersecret123");
    await page.fill("#companyName", "Titular Launch SL");
    await page.fill("#companyNif", DECA.carrierNif);
    await page.getByTestId("accept-terms").check();
    const [regRes] = await Promise.all([
      page.waitForResponse((r) => r.url().includes("/api/auth/register") && r.status() === 201),
      page.getByTestId("register-submit").click(),
    ]);
    const regBody = await regRes.json();
    await expect(page).toHaveURL(/\/verificar-email/);

    // D-053: authenticated but NOT YET verified — "Ya he confirmado mi cuenta"
    // is never proof by itself; it must find this false before real verification.
    await page.getByTestId("verify-email-continue").click();
    await expect(page.getByTestId("verify-email-not-yet")).toBeVisible();

    // real, server-side verification via the token the email actually carried
    const other = await page.context().newPage();
    await other.goto(`/verificar-email/${regBody.verifyTestToken}`);
    await expect(other.getByTestId("verify-email-success")).toBeVisible();
    await other.close();

    // NOW it finds the truth and proceeds — `next` sends it straight to /crear.
    await page.getByTestId("verify-email-continue").click();
    await expect(page).toHaveURL(/\/crear$/);

    // 7. The exact same draft is restored — nothing retyped.
    await expect(page.locator("#shipperName")).toHaveValue(DECA.shipperName);
    await page.getByTestId("wizard-next").click();
    await expect(page.locator("#loadLocationName")).toHaveValue(DECA.loadLocationName);
    await page.getByTestId("wizard-next").click();
    await expect(page.locator("#goods")).toHaveValue(DECA.goods);
    await expect(review).toContainText(DECA.shipperAddress);

    // 8-9. Now authenticated AND verified: generate once → result screen
    await page.getByTestId("wizard-generate").click();
    await expect(page).toHaveURL(/\/crear\/[a-z0-9]+/i, { timeout: 15_000 });
    await expect(page.getByRole("heading", { name: "DeCA generado" })).toBeVisible();

    // 7. Download link points straight at the public PDF URL
    const dl = page.getByTestId("result-download");
    const publicUrl = await dl.getAttribute("href");
    expect(publicUrl).toMatch(/\/d\/[A-Za-z0-9_-]+$/);

    // 8-9. QR-equivalent: fetch the public URL with a bare context — no auth, no
    // cookie, no interstitial — and get the PDF bytes directly.
    const insp = await request.get(publicUrl!);
    expect(insp.status()).toBe(200);
    expect(insp.headers()["content-type"]).toBe("application/pdf");
    expect(insp.headers()["set-cookie"]).toBeUndefined();
    expect(insp.headers()["x-robots-tag"]).toContain("noindex");
    const bytes = Buffer.from(await insp.body());
    expect(bytes.subarray(0, 5).toString()).toBe("%PDF-");
    const hash1 = createHash("sha256").update(bytes).digest("hex");
    // the QR encodes the configured host, not localhost-by-accident / wrong host
    expect(publicUrl!.startsWith(baseURL!)).toBe(true);

    // 10. Share with the driver — WhatsApp deep link carries the public URL
    await page.getByTestId("result-share-toggle").click();
    const wa = page.locator('a[href^="https://wa.me/"]').first();
    const waHref = await wa.getAttribute("href");
    expect(decodeURIComponent(waHref ?? "")).toContain(publicUrl!);

    // 11. Already owned at creation (registered before generating) — appears
    // in the workspace immediately, no separate claim step.
    await page.goto("/panel");
    await expect(
      page.getByText(`${DECA.loadLocationName} — ${DECA.loadLocationCity}`),
    ).toBeVisible();
    const after = await request.get(publicUrl!);
    expect(after.status()).toBe(200);
    expect(
      createHash("sha256")
        .update(Buffer.from(await after.body()))
        .digest("hex"),
    ).toBe(hash1);

    // 12. Duplicate → a brand-new independent DeCA, faster
    await page.goto("/panel");
    await page.getByTestId("app-repetir").click();
    await expect(page).toHaveURL(/\/crear\?from=/);
    await expect(page.locator("#carrierAddress")).toHaveValue(DECA.carrierAddress); // prefilled
    await page.getByTestId("wizard-next").click();
    await expect(page.locator("#loadLocationName")).toHaveValue(DECA.loadLocationName); // prefilled
    await expect(page.locator("#loadDate")).toHaveValue(""); // dates reset
    await expect(page.locator("#unloadDate")).toHaveValue("");
    await page.fill("#loadDate", "2026-10-20");
    await page.fill("#unloadDate", "2026-10-20");
    await page.getByTestId("wizard-next").click();
    await page.getByTestId("wizard-generate").click();
    await expect(page).toHaveURL(/\/crear\/[a-z0-9]+/i, { timeout: 15_000 });
    const dup = await page.getByTestId("result-download").getAttribute("href");
    expect(dup).not.toBe(publicUrl); // independent document, new token

    await page.goto("/panel/historico");
    await expect(page.getByText("2 documentos")).toBeVisible();
  });

  test("PRIORITY 1: signup wall is real — no session, no account, no document, ever", async ({
    browser,
  }) => {
    const ctx = await browser.newContext(); // zero cookies
    const page = await ctx.newPage();
    await page.goto("/crear");
    await fillWizardAnon(page);
    // no generate button to even click — the gate replaces it
    await expect(page.getByTestId("wizard-generate")).toHaveCount(0);
    await expect(page.getByTestId("auth-gate")).toBeVisible();

    // defense in depth: even a raw API call with no session is rejected
    const res = await ctx.request.post("/api/deca", {
      data: {
        shipper: { name: DECA.shipperName, nif: DECA.shipperNif, address: DECA.shipperAddress },
        carrier: { name: DECA.carrierName, nif: DECA.carrierNif, address: DECA.carrierAddress },
        loadLocation: {
          name: DECA.loadLocationName,
          address: DECA.loadLocationAddress,
          postalCode: DECA.loadLocationPostalCode,
          city: DECA.loadLocationCity,
          province: DECA.loadLocationProvince,
          country: DECA.loadLocationCountry,
        },
        unloadLocation: {
          name: DECA.unloadLocationName,
          address: DECA.unloadLocationAddress,
          postalCode: DECA.unloadLocationPostalCode,
          city: DECA.unloadLocationCity,
          province: DECA.unloadLocationProvince,
          country: DECA.unloadLocationCountry,
        },
        loadDate: DECA.loadDate,
        unloadDate: DECA.unloadDate,
        goods: DECA.goods,
        weight: DECA.weight,
        tractorPlate: DECA.tractorPlate,
      },
    });
    expect(res.status()).toBe(401);
    expect((await res.json()).error.code).toBe("auth_required");
    await ctx.close();
  });
});
