import { NextResponse } from "next/server";
import { validateDeca, DecaValidationError } from "@/lib/deca/validate";

export const runtime = "nodejs";

/**
 * Create a DeCA (F1). Validates the payload against R-2, persists the document
 * and its first version, and returns the ids + public token.
 *
 * A DeCA can only be finally generated by a registered, authenticated user
 * (PRIORITY 1, product hardening directive) — an unauthenticated caller is
 * rejected with 401 `auth_required` before validation ever runs. The wizard
 * lets a visitor fill every step anonymously; only this last, state-changing
 * call is gated, and it is enforced here server-side, never trusting the
 * client-side UI gate alone (security.md).
 *
 * Fails closed: any validation, persistence or (BUILD 08) render/storage failure
 * returns an error and creates nothing usable.
 */
export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: { code: "bad_request", message: "Cuerpo de la petición no válido." } },
      { status: 400 },
    );
  }

  const { getCurrentUser } = await import("@/lib/auth");
  const user = await getCurrentUser();
  if (!user?.companyId) {
    return NextResponse.json(
      {
        error: {
          code: "auth_required",
          message: "Crea una cuenta gratuita o inicia sesión para generar tu DeCA.",
        },
      },
      { status: 401 },
    );
  }
  // D-053: authenticated is not enough — the email must be verified, checked
  // fresh from the database (never a session/cookie claim) on every call.
  if (!user.emailVerifiedAt) {
    return NextResponse.json(
      {
        error: {
          code: "email_not_verified",
          message: "Verifica tu correo electrónico para generar el DeCA.",
        },
      },
      { status: 403 },
    );
  }
  const owner = { createdByUserId: user.id, companyId: user.companyId };

  let validated;
  try {
    validated = validateDeca(body);
  } catch (e) {
    if (e instanceof DecaValidationError) {
      return NextResponse.json(
        { error: { code: "validation", message: e.message, fields: e.fieldErrors } },
        { status: 422 },
      );
    }
    const { recordGenerationFailure } = await import("@/lib/deca/failures");
    const recorded = await recordGenerationFailure(e, {
      route: "POST /api/deca (validation)",
      authenticated: true,
      companyId: owner.companyId,
    });
    return NextResponse.json(
      {
        error: {
          code: "generation_failed",
          message: recorded.message,
          correlationId: recorded.correlationId,
          retryable: true,
        },
      },
      { status: 500 },
    );
  }

  const idempotencyKey = req.headers.get("idempotency-key") ?? undefined;

  try {
    // A retry with the SAME idempotency key (the wizard recovering from a
    // transient failure, #29) never creates a second document — `createDeca`
    // itself looks the key up first and returns the existing record.
    const { createDeca } = await import("@/lib/deca/persist");
    const created = await createDeca(validated, { idempotencyKey, ...owner });

    // WORKSPACE #24: bump "last used" on whichever saved records populated
    // this DeCA. Best-effort and never blocks the response — a bad/foreign
    // id in `usedSaved` is silently ignored (touchSavedUsage scopes every
    // update to this company).
    const usedSaved = (body as { usedSaved?: unknown } | null)?.usedSaved;
    if (usedSaved && typeof usedSaved === "object") {
      const u = usedSaved as Record<string, unknown>;
      const asId = (v: unknown) => (typeof v === "string" && v ? v : undefined);
      const companyIds = [asId(u.shipperId), asId(u.carrierId)].filter((v): v is string => !!v);
      const locationIds = [asId(u.loadLocationId), asId(u.unloadLocationId)].filter(
        (v): v is string => !!v,
      );
      const { touchSavedUsage } = await import("@/lib/data/saved");
      touchSavedUsage(owner.companyId, {
        companyIds,
        vehicleId: asId(u.vehicleId),
        locationIds,
      }).catch(() => {
        // never block or fail generation over a "last used" bookkeeping hiccup
      });
    }

    return NextResponse.json(
      {
        decaId: created.decaId,
        token: created.token,
        pdfSha256: created.pdfSha256,
        firstForCompany: created.firstForCompany,
        warnings: validated.warnings,
      },
      { status: 201 },
    );
  } catch (e) {
    // Stage-aware failure (#29): the client gets a calm message plus a short
    // correlation code; the stage itself is exposed only when FVD_DEBUG is on.
    const { recordGenerationFailure } = await import("@/lib/deca/failures");
    const recorded = await recordGenerationFailure(e, {
      route: "POST /api/deca",
      authenticated: true,
      companyId: owner.companyId,
    });
    return NextResponse.json(
      {
        error: {
          code: "generation_failed",
          message: recorded.message,
          correlationId: recorded.correlationId,
          retryable: true,
          ...(process.env.FVD_DEBUG === "1" ? { stage: recorded.stage } : {}),
        },
      },
      { status: 500 },
    );
  }
}
